### ISSUE TITLE
I can't delete a project without having to clear my entire datastorage

### ISSUE THREAD

**Issue by javier-tarazaga** [SuperblocksHQ/studio#15]
## Summary

Atm there is no way for me to actually delete a single project without having to actually clear my localstorage (therefore removing all my other projects which I can't export/import) 

## Motivation

We are doing this to make sure we all can add/delete projects easily within the tool. 

## Describe alternatives you've considered

There is no alternative atm as the only way to remove any project is by actually removing the localstorage which then will clear my entire collection of projects.

**Comment by filippsen** [comment]
Version "beta22" added the ability to delete a single project without having to manually touch "localstorage". In "Configure project" settings, there is a "Delete this DApp" link.

Adding projects and restoring the complete workspace have also been added since then, addressing the motivation factor described in this topic.
Thank you
