### ISSUE TITLE
Cryptic error message when trying to send interact transaction with low gas limit

### ISSUE THREAD

**Issue by filippsen** [SuperblocksHQ/studio#72]
## Message

> "Error: Error: Error: [ethjs-rpc] rpc error with payload {"id":585345760121,"jsonrpc":"2.0","params":["0xf8a8..."],"method":"eth_sendRawTransaction"} Error: intrinsic gas too low"

## Suggestion
The very last message would suffice.

**Comment by Bashlund** [comment]
Metamask won't let me send a tx without funds.
But I can reproduce this by creating five more accounts in Browser network and the last account does have 0 ether to it. So using that nonfunded account I get the error. It should be possible to put that erro message instead of 'Transaction hash', to alert the user that the tx did not get posted.
